/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementsystem;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import static java.lang.Thread.sleep;
import java.net.ConnectException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import oracle.jdbc.driver.OracleDriver;
import java.sql.*;

import java.util.*;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author Hitman
 */
public class WelcomePage extends javax.swing.JFrame {
Connection connect;
PreparedStatement pst=null;
ResultSet rs=null;
Connection connectdb2;

    /**
     * Creates new form WelcomePage
     */
    public WelcomePage(Connection conn,Connection connectdb2) {
        initComponents();
        connect=conn;
        this.connectdb2=connectdb2;
        try{  UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());}
      catch(Exception e){}
 
        
    }
     public WelcomePage() {
        initComponents();
        clock();
      try{  UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());}
      catch(Exception e){}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("jdbc:oracle:thin:@localhost:1521:XEPU").createEntityManager();
        hotelQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT h FROM Hotel h");
        hotelList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : hotelQuery.getResultList();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        hotelFrameWindow = new javax.swing.JButton();
        jRoomFrame = new javax.swing.JButton();
        jCustomerFrame = new javax.swing.JButton();
        jBooking_Details = new javax.swing.JButton();
        jPaymentFrame = new javax.swing.JButton();
        jGuestFrame = new javax.swing.JButton();
        jMembership = new javax.swing.JButton();
        jtime = new javax.swing.JLabel();
        jSystemtime = new javax.swing.JLabel();
        jLogOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu1.setText("File");
        jMenuBar3.add(jMenu1);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        jMenu2.setText("File");
        jMenuBar4.add(jMenu2);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("                           Hotel Management System ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jLabel2.setText("             Welcome to the Dashboard ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(292, 292, 292))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagementsystem/hotel-management-system-project.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        hotelFrameWindow.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hotelFrameWindow.setText("HOTEL");
        hotelFrameWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelFrameWindowActionPerformed(evt);
            }
        });

        jRoomFrame.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRoomFrame.setText("ROOM");
        jRoomFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRoomFrameActionPerformed(evt);
            }
        });

        jCustomerFrame.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCustomerFrame.setText("CUSTOMER");
        jCustomerFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCustomerFrameActionPerformed(evt);
            }
        });

        jBooking_Details.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBooking_Details.setText("BOOKING DETAILS");
        jBooking_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBooking_DetailsActionPerformed(evt);
            }
        });

        jPaymentFrame.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPaymentFrame.setText("PAYMENT");
        jPaymentFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPaymentFrameActionPerformed(evt);
            }
        });

        jGuestFrame.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jGuestFrame.setText("GUEST");
        jGuestFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuestFrameActionPerformed(evt);
            }
        });

        jMembership.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMembership.setText("Membership");
        jMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMembershipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPaymentFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jGuestFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(hotelFrameWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jRoomFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jCustomerFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jBooking_Details)
                        .addGap(114, 114, 114))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBooking_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCustomerFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRoomFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotelFrameWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPaymentFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGuestFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtime.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jSystemtime.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jSystemtime.setText(" System Time & Date");

        jLogOut.setBackground(new java.awt.Color(255, 51, 51));
        jLogOut.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLogOut.setText("Log Out");
        jLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jSystemtime, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jSystemtime, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtime, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1)
                .addGap(7, 7, 7))
        );

        getContentPane().add(jPanel3);
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hotelFrameWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelFrameWindowActionPerformed
       
        HotelFrame hf=new HotelFrame(connect,connectdb2);
         hf.setVisible(true);
         closeWelcome();
    }//GEN-LAST:event_hotelFrameWindowActionPerformed

    private void jRoomFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRoomFrameActionPerformed
        RoomFrame rf=new RoomFrame(connect,connectdb2);
         rf.setVisible(true);
         closeWelcome();
    }//GEN-LAST:event_jRoomFrameActionPerformed

    private void jCustomerFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCustomerFrameActionPerformed
       CustomerFrame rf=new CustomerFrame(connect,connectdb2);
         rf.setVisible(true);
         closeWelcome();  
    }//GEN-LAST:event_jCustomerFrameActionPerformed

    private void jPaymentFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPaymentFrameActionPerformed
         PaymentFrame rf=new PaymentFrame(connect,connectdb2);
         rf.setVisible(true);
         closeWelcome(); 
    }//GEN-LAST:event_jPaymentFrameActionPerformed

    private void jGuestFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuestFrameActionPerformed
        GuestFrame rf=new GuestFrame(connect,connectdb2);
         rf.setVisible(true);
         closeWelcome(); 
    }//GEN-LAST:event_jGuestFrameActionPerformed

    private void jMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMembershipActionPerformed
        MembershipFrame rf=new MembershipFrame(connect,connectdb2);
        rf.setVisible(true);
        closeWelcome(); 
    }//GEN-LAST:event_jMembershipActionPerformed

    private void jBooking_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBooking_DetailsActionPerformed
         BookingFrame rrf=new BookingFrame(connect,connectdb2);
        rrf.setVisible(true);
        closeWelcome(); 
        
    }//GEN-LAST:event_jBooking_DetailsActionPerformed

    private void jLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutActionPerformed
             
        try{
            connect.close();
            connectdb2.close();
            System.out.println("Connection closed");
        } catch(SQLException ex){
            System.out.println("error in closing connection");
        }

        JOptionPane.showMessageDialog(null,"You are successfully logged out. Thank you!!","Log out Menu",JOptionPane.INFORMATION_MESSAGE);
         
        closeWelcome();
        System.exit(0);
        




    }//GEN-LAST:event_jLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }
    
    public void clock()
    {
        Thread clock=new Thread(){
            public void run(){
                try{
                    for(;;){
                 Calendar cal=new GregorianCalendar();
        int day=cal.get(Calendar.DAY_OF_MONTH);
         int month=cal.get(Calendar.MONTH);
          int year=cal.get(Calendar.YEAR);
          
          int second=cal.get(Calendar.SECOND);
           int minute=cal.get(Calendar.MINUTE);
            int hour=cal.get(Calendar.HOUR);
           jtime.setText("Time: "+ hour+":"+minute+":"+second+" \n "+day+"/"+month+"/"+year);
                sleep(1000);
                }}
                catch(Exception e){
                    
                }}
            
        };
            clock.start();
   
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton hotelFrameWindow;
    private java.util.List<hotelmanagementsystem.Hotel> hotelList;
    private javax.persistence.Query hotelQuery;
    private javax.swing.JButton jBooking_Details;
    private javax.swing.JButton jCustomerFrame;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JButton jGuestFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jLogOut;
    private javax.swing.JButton jMembership;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jPaymentFrame;
    private javax.swing.JButton jRoomFrame;
    private javax.swing.JLabel jSystemtime;
    private javax.swing.JLabel jtime;
    // End of variables declaration//GEN-END:variables

private void closeWelcome()
{
    WindowEvent winClose= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClose);
}

}








